-- require("sj.core.custom.Git.autoPush")
require("sj.core.custom.Git.smartCopyPaste")
require("sj.core.custom.Git.readmeGenerate")
require("sj.core.custom.Git.readmeGen2")
require("sj.core.custom.Git.githubDescription")
require("sj.core.custom.Git.clone")
require("sj.core.custom.Git.autoPush2")
require("sj.core.custom.Git.githubRepoGenerateAndPush")
require("sj.core.custom.Git.Github")
